# Generated by Django 3.0.4 on 2020-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0002_comment_commentanswer_commentlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commentanswer',
            name='answer',
            field=models.TextField(),
        ),
    ]
