# Generated by Django 3.0.4 on 2020-04-06 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0004_auto_20200331_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='description',
        ),
        migrations.AddField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ClientCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.CharField(choices=[('RS', 'Restaurant'), ('CF', 'Cafe'), ('BR', 'Bar')], max_length=200)),
                ('customerEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YeOradaApp.Client')),
            ],
        ),
    ]
