# Generated by Django 3.0.4 on 2020-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0006_auto_20200406_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rateCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
