# Generated by Django 3.0.4 on 2020-04-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0007_auto_20200406_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='address1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
