# Generated by Django 3.0.4 on 2020-04-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0008_auto_20200406_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
