# Generated by Django 3.0.4 on 2020-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0011_auto_20200406_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='category',
            field=models.CharField(blank=True, choices=[('Restaurant', 'Restaurant'), ('Cafe', 'Cafe'), ('Bar', 'Bar')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientcuisine',
            name='cuisine',
            field=models.CharField(choices=[('Kebap', 'Kebap'), ('Grill', 'Grill'), ('Turkish', 'Turkish'), ('Pide', 'Pide'), ('Döner', 'Döner'), ('Fast Food', 'Fast Food'), ('Homemade', 'Homemade'), ('Seafood', 'Seafood'), ('Cafe & Restaurant', 'Cafe & Restaurant')], max_length=200),
        ),
    ]
