# Generated by Django 3.0.4 on 2020-04-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0012_auto_20200406_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='isLiked',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
