# Generated by Django 3.0.4 on 2020-04-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0012_auto_20200406_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcuisine',
            name='cuisine',
            field=models.CharField(choices=[('Kebap', 'Kebap'), ('Grill', 'Grill'), ('Turkish', 'Turkish'), ('Pide', 'Pide'), ('Döner', 'Döner'), ('Fast Food', 'Fast Food'), ('Homemade', 'Homemade'), ('Seafood', 'Seafood'), ('Cafe & Restaurant', 'Cafe & Restaurant'), ('Lunch', 'Lunch'), ('Breakfast', 'Breakfast'), ('Dinner', 'Dinner'), ('Pizza', 'Pizza'), ('Chinese', 'Chinese'), ('Korean', 'Korean')], max_length=200),
        ),
    ]
