# Generated by Django 3.0.4 on 2020-04-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0013_commentlike_isliked'),
        ('YeOradaApp', '0013_auto_20200409_1907'),
    ]

    operations = [
    ]
