# Generated by Django 3.0.4 on 2020-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0016_commentanswer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='likeNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
