# Generated by Django 3.0.4 on 2020-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0018_auto_20200415_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='defaultComment.jpg', upload_to='comment_pics'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image2',
            field=models.ImageField(default='defaultComment.jpg', upload_to='comment_pics'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image3',
            field=models.ImageField(default='defaultComment.jpg', upload_to='comment_pics'),
        ),
    ]
