# Generated by Django 3.0.4 on 2020-04-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0020_auto_20200423_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image1',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image2',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image3',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image4',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image5',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image6',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image7',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image8',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='image9',
            field=models.ImageField(default='defaultClient.jpg', upload_to='client_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(default='defaultLogo.jpg', upload_to='client_logo_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='menu1',
            field=models.ImageField(default='defaultMenu.jpg', upload_to='client_menu_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='menu2',
            field=models.ImageField(default='defaultMenu.jpg', upload_to='client_menu_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='menu3',
            field=models.ImageField(default='defaultMenu.jpg', upload_to='client_menu_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='menu4',
            field=models.ImageField(default='defaultMenu.jpg', upload_to='client_menu_pics'),
        ),
        migrations.AddField(
            model_name='client',
            name='menu5',
            field=models.ImageField(default='defaultMenu.jpg', upload_to='client_menu_pics'),
        ),
    ]
