# Generated by Django 3.0.4 on 2020-05-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0022_comment_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='YeOradaApp.Admin'),
        ),
    ]
