# Generated by Django 3.0.4 on 2020-05-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0023_comment_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=250, unique=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_surname', models.CharField(max_length=200)),
                ('owner_email', models.EmailField(max_length=254, verbose_name='email address')),
                ('owner_phone', models.CharField(max_length=200)),
                ('restaurant_phone', models.CharField(max_length=200)),
                ('restaurant_email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('workday_from', models.CharField(max_length=200)),
                ('workday_to', models.CharField(max_length=200)),
                ('workhour_from', models.CharField(max_length=200)),
                ('workhour_to', models.CharField(max_length=200)),
                ('restaurant_address', models.CharField(max_length=300)),
                ('will_be_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
