# Generated by Django 3.0.4 on 2020-05-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0024_clientapplicationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='forgot_password_code',
            field=models.IntegerField(default=0),
        ),
    ]
