# Generated by Django 3.0.4 on 2020-05-22 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0025_registereduser_forgot_password_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='forgot_password_code',
        ),
        migrations.CreateModel(
            name='ForgotPasswordCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
