# Generated by Django 3.0.4 on 2020-05-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0027_auto_20200522_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplicationform',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
