# Generated by Django 3.0.4 on 2020-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0028_clientapplicationform_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
