# Generated by Django 3.0.4 on 2020-05-24 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0029_client_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapplicationform',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
