# Generated by Django 3.0.4 on 2020-05-26 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YeOradaApp', '0031_auto_20200525_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='rateCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
